//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolBX.AwesomeMarkup.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToolBX.AwesomeMarkup.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attribute value is expected to be between quotes but it was not the case.
        /// </summary>
        internal static string AttributeValueMustBeQuoted {
            get {
                return ResourceManager.GetString("AttributeValueMustBeQuoted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t parse string.
        /// </summary>
        internal static string CannotParseString {
            get {
                return ResourceManager.GetString("CannotParseString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Markup language specifications has conflicting quote rules.
        /// </summary>
        internal static string ConflictingQuoteRules {
            get {
                return ResourceManager.GetString("ConflictingQuoteRules", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tags with both opening and closing slashes are not supported.
        /// </summary>
        internal static string ContainsSelfClosingAndClosingSlashes {
            get {
                return ResourceManager.GetString("ContainsSelfClosingAndClosingSlashes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Double quotes found in string but specifications disallow double quotes.
        /// </summary>
        internal static string DoubleQuotesDisallowed {
            get {
                return ResourceManager.GetString("DoubleQuotesDisallowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum recursion depth exceeded while parsing nested markup.
        /// </summary>
        internal static string MaxRecursionDepthExceeded {
            get {
                return ResourceManager.GetString("MaxRecursionDepthExceeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There should be the same amount of opening and closing brackets in &apos;{0}&apos; but there are {1} and {2} respectively.
        /// </summary>
        internal static string MismatchedBracketCount {
            get {
                return ResourceManager.GetString("MismatchedBracketCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attributes must have an even amount of quotes but had {0}.
        /// </summary>
        internal static string OddNumberOfQuotes {
            get {
                return ResourceManager.GetString("OddNumberOfQuotes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find a closing tag for &apos;{0}&apos;.
        /// </summary>
        internal static string OpeningTagWithoutClosingTag {
            get {
                return ResourceManager.GetString("OpeningTagWithoutClosingTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Single quotes found in string but specifications disallow single quotes.
        /// </summary>
        internal static string SingleQuotesDisallowed {
            get {
                return ResourceManager.GetString("SingleQuotesDisallowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not contain any valid parameters.
        /// </summary>
        internal static string StringDoesNotContainValidParameters {
            get {
                return ResourceManager.GetString("StringDoesNotContainValidParameters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0} in &apos;{1}&apos; has too many &apos;{2}&apos; symbols.
        /// </summary>
        internal static string TooManyAssignationSymbols {
            get {
                return ResourceManager.GetString("TooManyAssignationSymbols", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No linked tag found at index {0}.
        /// </summary>
        internal static string UnmatchedOpeningBracket {
            get {
                return ResourceManager.GetString("UnmatchedOpeningBracket", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found closing tags without matching opening tags.
        /// </summary>
        internal static string UnmatchedClosingTag {
            get {
                return ResourceManager.GetString("UnmatchedClosingTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unescaped opening bracket found inside a tag at index {0}.
        /// </summary>
        internal static string UnescapedBracketInTag {
            get {
                return ResourceManager.GetString("UnescapedBracketInTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opening bracket at index {0} has no matching closing bracket.
        /// </summary>
        internal static string UnclosedTag {
            get {
                return ResourceManager.GetString("UnclosedTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Closing tag &apos;{0}&apos; does not match the currently open tag &apos;{1}&apos;.
        /// </summary>
        internal static string MismatchedClosingTag {
            get {
                return ResourceManager.GetString("MismatchedClosingTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty or whitespace.
        /// </summary>
        internal static string ValueCannotBeWhitespace {
            get {
                return ResourceManager.GetString("ValueCannotBeWhitespace", resourceCulture);
            }
        }
    }
}
